_UI = {
    'es': {
        'nav_inicio':     'Inicio',
        'nav_coleccion':  'Colección',
        'nav_pendientes': 'Pendientes',
        'nav_collares':   'Collares',
        'nav_anillos':    'Anillos',
        'nav_brazaletes': 'Brazaletes',
        'nav_carrito':    'Carrito',
        'nav_mi_cuenta':  'Mi cuenta',
        'nav_salir':      'Salir',
        'nav_login':      'Iniciar sesión',
        'nav_register':   'Registrarse',
        'nav_cerrar':     'Cerrar sesión',
        'mob_menu':       'Menú',
        'mob_cats':       'Categorías',
    },
    'en': {
        'nav_inicio':     'Home',
        'nav_coleccion':  'Collection',
        'nav_pendientes': 'Earrings',
        'nav_collares':   'Necklaces',
        'nav_anillos':    'Rings',
        'nav_brazaletes': 'Bracelets',
        'nav_carrito':    'Cart',
        'nav_mi_cuenta':  'My account',
        'nav_salir':      'Sign out',
        'nav_login':      'Sign in',
        'nav_register':   'Register',
        'nav_cerrar':     'Sign out',
        'mob_menu':       'Menu',
        'mob_cats':       'Categories',
    },
    'fr': {
        'nav_inicio':     'Accueil',
        'nav_coleccion':  'Collection',
        'nav_pendientes': "Boucles d'oreilles",
        'nav_collares':   'Colliers',
        'nav_anillos':    'Bagues',
        'nav_brazaletes': 'Bracelets',
        'nav_carrito':    'Panier',
        'nav_mi_cuenta':  'Mon compte',
        'nav_salir':      'Déconnexion',
        'nav_login':      'Se connecter',
        'nav_register':   "S'inscrire",
        'nav_cerrar':     'Déconnexion',
        'mob_menu':       'Menu',
        'mob_cats':       'Catégories',
    },
    'de': {
        'nav_inicio':     'Startseite',
        'nav_coleccion':  'Kollektion',
        'nav_pendientes': 'Ohrringe',
        'nav_collares':   'Halsketten',
        'nav_anillos':    'Ringe',
        'nav_brazaletes': 'Armbänder',
        'nav_carrito':    'Warenkorb',
        'nav_mi_cuenta':  'Mein Konto',
        'nav_salir':      'Abmelden',
        'nav_login':      'Anmelden',
        'nav_register':   'Registrieren',
        'nav_cerrar':     'Abmelden',
        'mob_menu':       'Menü',
        'mob_cats':       'Kategorien',
    },
    'it': {
        'nav_inicio':     'Home',
        'nav_coleccion':  'Collezione',
        'nav_pendientes': 'Orecchini',
        'nav_collares':   'Collane',
        'nav_anillos':    'Anelli',
        'nav_brazaletes': 'Bracciali',
        'nav_carrito':    'Carrello',
        'nav_mi_cuenta':  'Il mio account',
        'nav_salir':      'Esci',
        'nav_login':      'Accedi',
        'nav_register':   'Registrati',
        'nav_cerrar':     'Esci',
        'mob_menu':       'Menu',
        'mob_cats':       'Categorie',
    },
    'cs': {
        'nav_inicio':     'Úvod',
        'nav_coleccion':  'Kolekce',
        'nav_pendientes': 'Náušnice',
        'nav_collares':   'Náhrdelníky',
        'nav_anillos':    'Prsteny',
        'nav_brazaletes': 'Náramky',
        'nav_carrito':    'Košík',
        'nav_mi_cuenta':  'Můj účet',
        'nav_salir':      'Odhlásit',
        'nav_login':      'Přihlásit se',
        'nav_register':   'Registrovat se',
        'nav_cerrar':     'Odhlásit se',
        'mob_menu':       'Menu',
        'mob_cats':       'Kategorie',
    },
}


def site_preferences(request):
    lang = request.session.get('site_lang', 'es')
    return {
        'site_lang':     lang,
        'site_currency': request.session.get('site_currency', 'EUR'),
        'nav':           _UI.get(lang, _UI['es']),
    }
