_UI = {
    'es': {
        # ── Navbar ──────────────────────────────────────────────────────────
        'nav_inicio':     'Inicio',
        'nav_coleccion':  'Colección',
        'nav_pendientes': 'Pendientes',
        'nav_collares':   'Collares',
        'nav_anillos':    'Anillos',
        'nav_brazaletes': 'Brazaletes',
        'nav_carrito':    'Carrito',
        'nav_mi_cuenta':  'Mi cuenta',
        'nav_salir':      'Salir',
        'nav_login':      'Iniciar sesión',
        'nav_register':   'Registrarse',
        'nav_cerrar':     'Cerrar sesión',
        'mob_menu':       'Menú',
        'mob_cats':       'Categorías',

        # ── School disclaimer ────────────────────────────────────────────────
        'school_disclaimer': '⚠️ Aviso: Este sitio web es un proyecto académico — no es una tienda real. Los pedidos no se procesan.',

        # ── Announcement bar ────────────────────────────────────────────────
        'ann_msg1': 'Envío gratis a partir de €100',
        'ann_msg2': 'Oferta limitada — hasta -50%',
        'ann_msg3': '+2.000 clientas satisfechas · Valoración 4.9',

        # ── Index — Hero ─────────────────────────────────────────────────────
        'hero_new_collection': 'Nueva Colección 2026',
        'hero_tagline':        'Joyería femenina · Elegancia mediterránea',
        'hero_cta':            'VER COLECCIÓN',

        # ── Index — Categories ───────────────────────────────────────────────
        'cats_title': 'Nuestras Categorías',
        'cats_sub':   'DESCUBRE NUESTRA COLECCIÓN',
        'cat_all':    'Todos',

        # ── Index — Countdown ────────────────────────────────────────────────
        'offer_label': 'OFERTA LIMITADA',
        'offer_text':  'Hasta -50% en toda la colección',
        'time_hours':  'HORAS',
        'time_min':    'MIN',
        'time_seg':    'SEG',

        # ── Index — Bestsellers ──────────────────────────────────────────────
        'bestsellers_title': 'Más Vendidos',
        'bestsellers_sub':   'NUESTROS FAVORITOS',
        'sale_badge':        'OFERTA',
        'btn_add':           '＋ Añadir',

        # ── Index — Story ────────────────────────────────────────────────────
        'story_label': 'NUESTRA HISTORIA',
        'story_title': 'Lo que nunca te he contado',
        'story_p1':    'Hace unos años, algo cambió en mi vida. Me di cuenta de que cada mujer merece sentirse especial cada día — no solo en las ocasiones grandes, sino en los momentos pequeños del día a día.',
        'story_p2':    'Por eso decidí crear Isabella Barcelona. Cada pieza está elegida con cuidado, para que te acompañe en tus momentos preciosos — desde el café de la mañana hasta la cena con amigas.',
        'story_p3':    'Esto no es una estrategia de marketing. Es simplemente mi manera de decirte gracias — a cada una de vosotras que me habéis dado vuestra confianza.',
        'story_sign':  'Con amor, Isabella',

        # ── Index — Reviews ──────────────────────────────────────────────────
        'reviews_title': 'Opiniones Verificadas',
        'reviews_sub':   'NUESTRAS CLIENTAS',
        'reviews_count': '+2.000 reseñas verificadas',

        # ── Index — FAQ ──────────────────────────────────────────────────────
        'faq_label': 'PREGUNTAS FRECUENTES',
        'faq_title': '¿Tienes alguna duda?',
        'faq_q1': '¿Cuánto tarda el envío y cuánto cuesta?',
        'faq_a1': 'Los pedidos se envían en 24–48 h laborables desde Barcelona. El envío estándar a España tarda 2–4 días hábiles por €3,90. A partir de €100 el envío es completamente gratuito. Para Baleares, Canarias y Europa el plazo es de 5–8 días hábiles. Recibirás un número de seguimiento por email.',
        'faq_q2': '¿Puedo devolver o cambiar mi pedido?',
        'faq_a2': 'Sí, tienes 30 días desde la recepción para devolver cualquier artículo sin justificación. La devolución es gratuita: escríbenos a hola@isabellabcn.com y te enviaremos una etiqueta prepagada. El reembolso se realiza en 3–5 días hábiles. Los artículos deben estar sin usar y con su embalaje original.',
        'faq_q3': '¿Qué materiales usáis en vuestras joyas?',
        'faq_a3': 'Trabajamos con materiales hipoalergénicos de alta calidad: plata de ley 925, acero inoxidable 316L y plata bañada en oro real de 14k o en oro rosa. Sin níquel ni plomo. Todas las piedras son zircónitas de alta calidad resistentes al agua y al sudor.',
        'faq_q4': '¿Cómo sé qué talla de anillo elegir?',
        'faq_a4': 'Mide el diámetro interior de un anillo que te quede bien: talla 48 = 15,3 mm · talla 50 = 15,9 mm · talla 52 = 16,5 mm · talla 54 = 17,2 mm. Entre dos tallas, elige la mayor. Muchos de nuestros anillos son ajustables.',
        'faq_q5': '¿Qué métodos de pago aceptáis?',
        'faq_a5': 'Aceptamos tarjeta de crédito y débito (Visa, Mastercard, Amex) y PayPal. Los pagos con tarjeta se procesan a través de Stripe con cifrado SSL. No almacenamos ningún dato bancario en nuestros servidores.',
        'faq_q6': '¿Cómo cuido correctamente mis joyas?',
        'faq_a6': '1) Guárdalas en la cajita que recibirás con tu pedido. 2) Evita el contacto con perfumes y cremas — póntelas siempre la última. 3) Límpialas con un paño suave y seco. 4) Aunque son resistentes al agua, te recomendamos quitártelas antes de nadar en el mar o en cloro.',

        # ── Coleccion ────────────────────────────────────────────────────────
        'coleccion_sub':      'Isabella Barcelona · 2026',
        'sort_newest':        'Novedades',
        'sort_price_asc':     'Precio ↑',
        'sort_price_desc':    'Precio ↓',
        'product_singular':   'producto',
        'product_plural':     'productos',
        'col_empty_title':    'No hay productos en esta categoría',
        'col_empty_text':     'Prueba con otra categoría o explora toda la colección.',
        'col_empty_cta':      'Ver Todo',

        # ── Cart ─────────────────────────────────────────────────────────────
        'cart_title':         'Tu Carrito',
        'cart_update':        'Actualizar',
        'cart_remove':        '✕ Eliminar',
        'cart_continue':      '← Continuar comprando',
        'cart_summary':       'RESUMEN DEL PEDIDO',
        'cart_subtotal':      'Subtotal',
        'cart_shipping':      'Envío',
        'cart_free':          'Gratis',
        'cart_calculated':    'Calculado al pagar',
        'cart_total':         'Total',
        'cart_free_label':    'Envío gratuito',
        'cart_free_pre':      '¡Añade ',
        'cart_free_post':     ' más para envío gratuito!',
        'cart_free_applied':  '¡Envío gratuito aplicado!',
        'cart_checkout':      'Finalizar Compra',
        'cart_secure':        'Pago seguro',
        'cart_returns':       'Devolución gratuita',
        'cart_empty_title':   'Tu carrito está vacío',
        'cart_empty_text':    'Descubre nuestra colección y encuentra la joya perfecta para ti.',
        'cart_empty_cta':     'Ver Colección',

        # ── Checkout ─────────────────────────────────────────────────────────
        'ck_bc_cart':         'Carrito',
        'ck_bc_payment':      'Pago',
        'ck_contact':         'Datos de contacto',
        'ck_fullname':        'Nombre completo *',
        'ck_phone':           'Teléfono',
        'ck_address':         'Dirección de envío',
        'ck_street':          'Calle y número *',
        'ck_city':            'Ciudad *',
        'ck_postal':          'Código postal *',
        'ck_country':         'País *',
        'ck_payment_method':  'Método de pago',
        'ck_card':            'Tarjeta de crédito',
        'ck_card_sub':        'Visa · Mastercard · Amex',
        'ck_paypal_sub':      'Pago rápido y seguro',
        'ck_card_number':     'Número de tarjeta',
        'ck_expiry':          'Caducidad',
        'ck_cvv':             'CVV',
        'ck_ssl':             'Pago seguro con cifrado SSL. Los datos de tu tarjeta no se almacenan en nuestros servidores.',
        'ck_paypal_redirect': 'Al confirmar el pedido serás redirigida a PayPal para completar el pago de forma segura.',
        'ck_submit':          'Confirmar pedido',
        'ck_terms':           'Al confirmar, aceptas nuestros',
        'ck_terms_link1':     'Términos de venta',
        'ck_terms_link2':     'Política de devoluciones',
        'ck_qty_label':       'Cantidad:',
        'ck_add_free_pre':    'Añade ',
        'ck_add_free_post':   ' más para envío gratuito',
        'ck_delivery_est':    'Entrega estimada: 2–4 días hábiles',
        'ck_returns30':       'Devolución gratuita en 30 días',
        'ck_secure_pay':      'Pago 100% seguro',
        'ck_back_cart':       '← Volver al carrito',

        # ── Gracias / Thank you ──────────────────────────────────────────────
        'ty_confirmed':    'PEDIDO CONFIRMADO',
        'ty_title':        '¡Gracias por tu pedido!',
        'ty_text':         'Hemos recibido tu pedido y lo estamos preparando con mucho cariño. Recibirás un email de confirmación en breve.',
        'ty_order_number': 'NÚMERO DE PEDIDO',
        'ty_detail':       'DETALLE DEL PEDIDO',
        'ty_qty_label':    'Cantidad:',
        'ty_subtotal':     'Subtotal',
        'ty_shipping':     'Envío',
        'ty_free':         'Gratis',
        'ty_total':        'Total',
        'ty_ship_addr':    'DIRECCIÓN DE ENVÍO',
        'ty_delivery':     'Entrega estimada en 2–4 días hábiles. Te enviaremos el número de seguimiento por email.',
        'ty_continue':     'Seguir comprando',
        'ty_my_orders':    'Mis pedidos',
        'ty_sign':         'Con amor, Isabella',

        # ── Product detail ───────────────────────────────────────────────────
        'pd_sale':              'OFERTA',
        'pd_enlarge':           'Ampliar',
        'pd_units_pre':         '¡Solo quedan ',
        'pd_units_post':        ' unidades!',
        'pd_in_stock_pre':      '✓ En stock — ',
        'pd_in_stock_post':     ' unidades disponibles',
        'pd_out_stock':         '✗ Sin stock',
        'pd_qty_label':         'CANTIDAD',
        'pd_add_cart':          'Añadir al carrito',
        'pd_no_stock_btn':      'Sin stock',
        'pd_free_ship':         'Envío gratuito a partir de €100',
        'pd_secure':            'Pago 100% seguro — Stripe & PayPal',
        'pd_returns':           'Devolución gratuita en 30 días',
        'pd_reviews_rating':    '4.9/5 — más de 2.000 reseñas verificadas',
        'pd_acc_details':       'Detalles del producto',
        'pd_acc_details_dflt':  'Joya de alta calidad fabricada con materiales premium. Baño de oro de 18K, hipoalergénica y resistente al agua.',
        'pd_acc_quality':       'Calidad',
        'pd_acc_quality_text':  'Ofrecemos garantía de 365 días en cada joya. Nuestras joyas no se decoloran y cumplen con estrictas directrices de calidad. Para mantener tus joyas bonitas durante más tiempo, recomendamos evitar el contacto con el agua.',
        'pd_acc_tips':          'Consejos de uso',
        'pd_acc_tips_text':     'Mantén siempre tus joyas fuera del alcance de los niños. Retira tus joyas en la ducha, al dormir, en la sauna o durante actividades deportivas.',
        'pd_related':           'También te puede gustar',
        'pd_sp_ago':            'Hace unos minutos · Isabella Barcelona',
        'pd_sp_from':           'de',
        'pd_sp_bought':         'acaba de comprar este producto',

        # ── Login ────────────────────────────────────────────────────────────
        'login_welcome':     'BIENVENIDA',
        'login_title':       'Iniciar Sesión',
        'login_user_label':  'USUARIO O EMAIL',
        'login_pass_label':  'CONTRASEÑA',
        'login_btn':         'Entrar',
        'login_no_account':  '¿Aún no tienes cuenta?',
        'login_create':      'CREAR CUENTA',

        # ── Register ─────────────────────────────────────────────────────────
        'reg_label':         'ÚNETE',
        'reg_title':         'Crear Cuenta',
        'reg_subtitle':      'Forma parte de la familia Isabella Barcelona',
        'reg_username':      'NOMBRE DE USUARIO',
        'reg_pass':          'CONTRASEÑA',
        'reg_pass_confirm':  'CONFIRMAR CONTRASEÑA',
        'reg_btn':           'Crear Cuenta',
        'reg_terms':         'Al crear una cuenta aceptas nuestras',
        'reg_terms_link1':   'Condiciones de venta',
        'reg_terms_link2':   'Política de privacidad',
        'reg_have_account':  '¿Ya tienes cuenta?',
        'reg_login_link':    'INICIAR SESIÓN',

        # ── Mi cuenta ────────────────────────────────────────────────────────
        'account_label':         'MI CUENTA',
        'account_hello':         'Hola,',
        'account_logout_btn':    'CERRAR SESIÓN',
        'account_stat_orders':   'PEDIDOS',
        'account_stat_shipped':  'ENVIADOS',
        'account_stat_member':   'Miembro',
        'account_stat_family':   'ISABELLA FAMILY',
        'account_my_orders':     'MIS PEDIDOS',
        'table_order':           'PEDIDO',
        'table_date':            'FECHA',
        'table_status':          'ESTADO',
        'table_total':           'TOTAL',
        'status_pending':        'PENDIENTE',
        'status_paid':           'PAGADO',
        'status_shipped':        'ENVIADO',
        'status_delivered':      'ENTREGADO',
        'status_cancelled':      'CANCELADO',
        'account_no_orders':     'Aún no tienes pedidos',
        'account_no_orders_txt': 'Descubre nuestra colección y encuentra tu primera joya.',
        'account_explore':       'Ver Colección',

        # ── Footer ───────────────────────────────────────────────────────────
        'footer_newsletter_title': 'ÚNETE A LA FAMILIA',
        'footer_newsletter_text':  'Recibe en primicia nuestras nuevas colecciones y ofertas exclusivas.',
        'footer_newsletter_ph':    'Tu dirección email',
        'footer_mission_title':    'NUESTRA MISIÓN',
        'footer_mission_text':     'Isabella Barcelona nació de una idea simple — que cada mujer merece llevar algo bello cada día.',
        'footer_mission_sign':     'Con amor, Isabella',
        'footer_info_title':       'INFORMACIÓN',
        'footer_faq_link':         'Preguntas frecuentes',
        'footer_story_link':       'Nuestra Historia',
        'footer_legal_link':       'Aviso Legal',
        'footer_terms_link':       'Condiciones de venta',
        'footer_returns_link':     'Política de devoluciones',
        'footer_service_title':    'ATENCIÓN AL CLIENTE',
        'footer_service_text1':    '¿Tienes alguna pregunta o necesitas ayuda?',
        'footer_service_text2':    'Nuestro equipo está aquí para acompañarte.',
        'footer_hours':            'Lunes – Viernes: 10:00 – 18:00',
        'footer_copyright':        '© 2026 Isabella Barcelona · Todos los derechos reservados',

        # ── Exit popup ────────────────────────────────────────────────────────
        'exit_tagline':       'No te vayas aún',
        'exit_title':         '¡Espera! Tu carrito<br>te está esperando',
        'exit_text':          'Como regalo especial, usa este código exclusivo y llévate un 10% de descuento en tu pedido:',
        'exit_code_label':    'Tu código exclusivo',
        'exit_discount_txt':  '10% de descuento en tu pedido',
        'exit_cta':           'Quiero mi descuento →',
        'exit_dismiss':       'No, gracias — prefiero pagar más',
    },

    'en': {
        # ── Navbar ──────────────────────────────────────────────────────────
        'nav_inicio':     'Home',
        'nav_coleccion':  'Collection',
        'nav_pendientes': 'Earrings',
        'nav_collares':   'Necklaces',
        'nav_anillos':    'Rings',
        'nav_brazaletes': 'Bracelets',
        'nav_carrito':    'Cart',
        'nav_mi_cuenta':  'My account',
        'nav_salir':      'Sign out',
        'nav_login':      'Sign in',
        'nav_register':   'Register',
        'nav_cerrar':     'Sign out',
        'mob_menu':       'Menu',
        'mob_cats':       'Categories',

        'school_disclaimer': '⚠️ Notice: This website is a school project — it is not a real shop. Orders are not processed.',

        'ann_msg1': 'Free shipping on orders over €100',
        'ann_msg2': 'Limited offer — up to -50% off',
        'ann_msg3': '+2,000 satisfied customers · Rating 4.9',

        'hero_new_collection': 'New Collection 2026',
        'hero_tagline':        'Feminine jewellery · Mediterranean elegance',
        'hero_cta':            'VIEW COLLECTION',

        'cats_title': 'Our Categories',
        'cats_sub':   'DISCOVER OUR COLLECTION',
        'cat_all':    'All',

        'offer_label': 'LIMITED OFFER',
        'offer_text':  'Up to -50% on the entire collection',
        'time_hours':  'HOURS',
        'time_min':    'MIN',
        'time_seg':    'SEC',

        'bestsellers_title': 'Best Sellers',
        'bestsellers_sub':   'OUR FAVOURITES',
        'sale_badge':        'SALE',
        'btn_add':           '＋ Add',

        'story_label': 'OUR STORY',
        'story_title': 'What I have never told you',
        'story_p1':    'A few years ago, something changed in my life. I realised that every woman deserves to feel special every day — not just on big occasions, but in the small moments of everyday life.',
        'story_p2':    'That is why I decided to create Isabella Barcelona. Every piece is chosen with care, to accompany you in your precious moments — from your morning coffee to dinner with friends.',
        'story_p3':    'This is not a marketing strategy. It is simply my way of saying thank you — to each and every one of you who has given me your trust.',
        'story_sign':  'With love, Isabella',

        'reviews_title': 'Verified Reviews',
        'reviews_sub':   'OUR CUSTOMERS',
        'reviews_count': '+2,000 verified reviews',

        'faq_label': 'FREQUENTLY ASKED QUESTIONS',
        'faq_title': 'Any questions?',
        'faq_q1': 'How long does delivery take and what does it cost?',
        'faq_a1': 'Orders ship within 24–48 business hours from Barcelona. Standard shipping to Spain takes 2–4 business days for €3.90. Orders over €100 qualify for free shipping. For Europe, allow 5–8 business days. You will receive a tracking number by email once your order leaves our warehouse.',
        'faq_q2': 'Can I return or exchange my order?',
        'faq_a2': 'Yes, you have 30 days from delivery to return any item without giving a reason. Returns are free — write to hola@isabellabcn.com and we will send a prepaid return label. Refunds are processed within 3–5 business days. Items must be unused and in their original packaging.',
        'faq_q3': 'What materials do you use in your jewellery?',
        'faq_a3': 'We use exclusively hypoallergenic, high-quality materials: 925 sterling silver, 316L stainless steel, and silver plated with real 14k or rose gold. No nickel or lead. All stones are high-quality cubic zirconia resistant to water and sweat.',
        'faq_q4': 'How do I choose my ring size?',
        'faq_a4': 'The easiest way is to measure the inner diameter of a ring that fits you: size 48 = 15.3 mm · size 50 = 15.9 mm · size 52 = 16.5 mm · size 54 = 17.2 mm. If between sizes, choose the larger. Many of our rings are adjustable.',
        'faq_q5': 'What payment methods do you accept?',
        'faq_a5': 'We accept credit and debit cards (Visa, Mastercard, American Express) and PayPal. All card payments are processed through Stripe with SSL encryption. We do not store any banking data on our servers.',
        'faq_q6': 'How do I care for my jewellery?',
        'faq_a6': '1) Store in the box included with your order to avoid scratches. 2) Avoid contact with perfumes and creams — put jewellery on last. 3) Clean with a soft, dry cloth. 4) Although our jewellery is water-resistant, we recommend removing it before swimming in the sea or in chlorinated water.',

        'coleccion_sub':      'Isabella Barcelona · 2026',
        'sort_newest':        'Newest',
        'sort_price_asc':     'Price ↑',
        'sort_price_desc':    'Price ↓',
        'product_singular':   'product',
        'product_plural':     'products',
        'col_empty_title':    'No products in this category',
        'col_empty_text':     'Try another category or explore the full collection.',
        'col_empty_cta':      'View All',

        'cart_title':         'Your Cart',
        'cart_update':        'Update',
        'cart_remove':        '✕ Remove',
        'cart_continue':      '← Continue shopping',
        'cart_summary':       'ORDER SUMMARY',
        'cart_subtotal':      'Subtotal',
        'cart_shipping':      'Shipping',
        'cart_free':          'Free',
        'cart_calculated':    'Calculated at checkout',
        'cart_total':         'Total',
        'cart_free_label':    'Free shipping',
        'cart_free_pre':      'Add ',
        'cart_free_post':     ' more for free shipping!',
        'cart_free_applied':  'Free shipping applied!',
        'cart_checkout':      'Checkout',
        'cart_secure':        'Secure payment',
        'cart_returns':       'Free returns',
        'cart_empty_title':   'Your cart is empty',
        'cart_empty_text':    'Discover our collection and find the perfect jewel for you.',
        'cart_empty_cta':     'View Collection',

        'ck_bc_cart':         'Cart',
        'ck_bc_payment':      'Payment',
        'ck_contact':         'Contact details',
        'ck_fullname':        'Full name *',
        'ck_phone':           'Phone',
        'ck_address':         'Shipping address',
        'ck_street':          'Street and number *',
        'ck_city':            'City *',
        'ck_postal':          'Postcode *',
        'ck_country':         'Country *',
        'ck_payment_method':  'Payment method',
        'ck_card':            'Credit card',
        'ck_card_sub':        'Visa · Mastercard · Amex',
        'ck_paypal_sub':      'Fast and secure payment',
        'ck_card_number':     'Card number',
        'ck_expiry':          'Expiry',
        'ck_cvv':             'CVV',
        'ck_ssl':             'Secure payment with SSL encryption. Your card details are not stored on our servers.',
        'ck_paypal_redirect': 'On confirming your order you will be redirected to PayPal to complete payment securely.',
        'ck_submit':          'Confirm order',
        'ck_terms':           'By confirming, you accept our',
        'ck_terms_link1':     'Terms of sale',
        'ck_terms_link2':     'Return policy',
        'ck_qty_label':       'Qty:',
        'ck_add_free_pre':    'Add ',
        'ck_add_free_post':   ' more for free shipping',
        'ck_delivery_est':    'Estimated delivery: 2–4 business days',
        'ck_returns30':       'Free returns within 30 days',
        'ck_secure_pay':      '100% secure payment',
        'ck_back_cart':       '← Back to cart',

        'ty_confirmed':    'ORDER CONFIRMED',
        'ty_title':        'Thank you for your order!',
        'ty_text':         'We have received your order and are preparing it with great care. You will receive a confirmation email shortly.',
        'ty_order_number': 'ORDER NUMBER',
        'ty_detail':       'ORDER DETAILS',
        'ty_qty_label':    'Qty:',
        'ty_subtotal':     'Subtotal',
        'ty_shipping':     'Shipping',
        'ty_free':         'Free',
        'ty_total':        'Total',
        'ty_ship_addr':    'SHIPPING ADDRESS',
        'ty_delivery':     'Estimated delivery in 2–4 business days. We will send your tracking number by email.',
        'ty_continue':     'Continue shopping',
        'ty_my_orders':    'My orders',
        'ty_sign':         'With love, Isabella',

        'pd_sale':              'SALE',
        'pd_enlarge':           'Enlarge',
        'pd_units_pre':         'Only ',
        'pd_units_post':        ' units left!',
        'pd_in_stock_pre':      '✓ In stock — ',
        'pd_in_stock_post':     ' units available',
        'pd_out_stock':         '✗ Out of stock',
        'pd_qty_label':         'QUANTITY',
        'pd_add_cart':          'Add to cart',
        'pd_no_stock_btn':      'Out of stock',
        'pd_free_ship':         'Free shipping on orders over €100',
        'pd_secure':            '100% secure payment — Stripe & PayPal',
        'pd_returns':           'Free returns within 30 days',
        'pd_reviews_rating':    '4.9/5 — over 2,000 verified reviews',
        'pd_acc_details':       'Product details',
        'pd_acc_details_dflt':  'High-quality jewel made with premium materials. 18K gold plating, hypoallergenic and water-resistant.',
        'pd_acc_quality':       'Quality',
        'pd_acc_quality_text':  'We offer a 365-day guarantee on every jewel. Our jewellery does not tarnish and meets strict quality standards. To keep your jewellery beautiful longer, we recommend avoiding contact with water.',
        'pd_acc_tips':          'Care tips',
        'pd_acc_tips_text':     'Always keep your jewellery out of reach of children. Remove your jewellery when showering, sleeping, in the sauna or during sports activities.',
        'pd_related':           'You may also like',
        'pd_sp_ago':            'A few minutes ago · Isabella Barcelona',
        'pd_sp_from':           'from',
        'pd_sp_bought':         'just bought this product',

        'login_welcome':     'WELCOME',
        'login_title':       'Sign In',
        'login_user_label':  'USERNAME OR EMAIL',
        'login_pass_label':  'PASSWORD',
        'login_btn':         'Sign in',
        'login_no_account':  "Don't have an account yet?",
        'login_create':      'CREATE ACCOUNT',

        'reg_label':         'JOIN US',
        'reg_title':         'Create Account',
        'reg_subtitle':      'Become part of the Isabella Barcelona family',
        'reg_username':      'USERNAME',
        'reg_pass':          'PASSWORD',
        'reg_pass_confirm':  'CONFIRM PASSWORD',
        'reg_btn':           'Create Account',
        'reg_terms':         'By creating an account you accept our',
        'reg_terms_link1':   'Terms of sale',
        'reg_terms_link2':   'Privacy policy',
        'reg_have_account':  'Already have an account?',
        'reg_login_link':    'SIGN IN',

        'account_label':         'MY ACCOUNT',
        'account_hello':         'Hello,',
        'account_logout_btn':    'SIGN OUT',
        'account_stat_orders':   'ORDERS',
        'account_stat_shipped':  'SHIPPED',
        'account_stat_member':   'Member',
        'account_stat_family':   'ISABELLA FAMILY',
        'account_my_orders':     'MY ORDERS',
        'table_order':           'ORDER',
        'table_date':            'DATE',
        'table_status':          'STATUS',
        'table_total':           'TOTAL',
        'status_pending':        'PENDING',
        'status_paid':           'PAID',
        'status_shipped':        'SHIPPED',
        'status_delivered':      'DELIVERED',
        'status_cancelled':      'CANCELLED',
        'account_no_orders':     'No orders yet',
        'account_no_orders_txt': 'Discover our collection and find your first jewel.',
        'account_explore':       'View Collection',

        # ── Footer ───────────────────────────────────────────────────────────
        'footer_newsletter_title': 'JOIN THE FAMILY',
        'footer_newsletter_text':  'Be the first to receive our new collections and exclusive offers.',
        'footer_newsletter_ph':    'Your email address',
        'footer_mission_title':    'OUR MISSION',
        'footer_mission_text':     'Isabella Barcelona was born from a simple idea — that every woman deserves to wear something beautiful every day.',
        'footer_mission_sign':     'With love, Isabella',
        'footer_info_title':       'INFORMATION',
        'footer_faq_link':         'FAQ',
        'footer_story_link':       'Our Story',
        'footer_legal_link':       'Legal Notice',
        'footer_terms_link':       'Terms of Sale',
        'footer_returns_link':     'Return Policy',
        'footer_service_title':    'CUSTOMER SERVICE',
        'footer_service_text1':    'Have a question or need help?',
        'footer_service_text2':    'Our team is here to assist you.',
        'footer_hours':            'Monday – Friday: 10:00 – 18:00',
        'footer_copyright':        '© 2026 Isabella Barcelona · All rights reserved',

        # ── Exit popup ────────────────────────────────────────────────────────
        'exit_tagline':       "Don't leave yet",
        'exit_title':         'Wait! Your cart<br>is waiting for you',
        'exit_text':          'As a special gift, use this exclusive code and get 10% off your order:',
        'exit_code_label':    'Your exclusive code',
        'exit_discount_txt':  '10% off your order',
        'exit_cta':           'Get my discount →',
        'exit_dismiss':       'No thanks — I prefer to pay full price',
    },

    'fr': {
        # ── Navbar ──────────────────────────────────────────────────────────
        'nav_inicio':     'Accueil',
        'nav_coleccion':  'Collection',
        'nav_pendientes': "Boucles d'oreilles",
        'nav_collares':   'Colliers',
        'nav_anillos':    'Bagues',
        'nav_brazaletes': 'Bracelets',
        'nav_carrito':    'Panier',
        'nav_mi_cuenta':  'Mon compte',
        'nav_salir':      'Déconnexion',
        'nav_login':      'Se connecter',
        'nav_register':   "S'inscrire",
        'nav_cerrar':     'Déconnexion',
        'mob_menu':       'Menu',
        'mob_cats':       'Catégories',

        'school_disclaimer': "⚠️ Avis : Ce site est un projet scolaire — ce n'est pas une vraie boutique. Les commandes ne sont pas traitées.",

        'ann_msg1': 'Livraison gratuite à partir de €100',
        'ann_msg2': "Offre limitée — jusqu'à -50%",
        'ann_msg3': '+2 000 clientes satisfaites · Note 4.9',

        'hero_new_collection': 'Nouvelle Collection 2026',
        'hero_tagline':        'Bijoux féminins · Élégance méditerranéenne',
        'hero_cta':            'VOIR LA COLLECTION',

        'cats_title': 'Nos Catégories',
        'cats_sub':   'DÉCOUVREZ NOTRE COLLECTION',
        'cat_all':    'Tout',

        'offer_label': 'OFFRE LIMITÉE',
        'offer_text':  "Jusqu'à -50% sur toute la collection",
        'time_hours':  'HEURES',
        'time_min':    'MIN',
        'time_seg':    'SEC',

        'bestsellers_title': 'Meilleures Ventes',
        'bestsellers_sub':   'NOS FAVORIS',
        'sale_badge':        'PROMO',
        'btn_add':           '＋ Ajouter',

        'story_label': 'NOTRE HISTOIRE',
        'story_title': "Ce que je ne vous ai jamais dit",
        'story_p1':    "Il y a quelques années, quelque chose a changé dans ma vie. J'ai réalisé que chaque femme mérite de se sentir spéciale chaque jour — pas seulement lors des grandes occasions, mais dans les petits moments du quotidien.",
        'story_p2':    "C'est pourquoi j'ai décidé de créer Isabella Barcelona. Chaque pièce est choisie avec soin, pour vous accompagner dans vos moments précieux — du café du matin au dîner entre amies.",
        'story_p3':    "Ce n'est pas une stratégie marketing. C'est simplement ma façon de vous remercier — à chacune d'entre vous qui m'a accordé sa confiance.",
        'story_sign':  'Avec amour, Isabella',

        'reviews_title': 'Avis Vérifiés',
        'reviews_sub':   'NOS CLIENTES',
        'reviews_count': '+2 000 avis vérifiés',

        'faq_label': 'QUESTIONS FRÉQUENTES',
        'faq_title': 'Vous avez des questions ?',
        'faq_q1': 'Combien de temps prend la livraison et combien coûte-t-elle ?',
        'faq_a1': "Les commandes sont expédiées sous 24–48 h ouvrables depuis Barcelone. La livraison standard en Europe prend 5–8 jours ouvrables pour €3,90. Livraison gratuite à partir de €100. Vous recevrez un numéro de suivi par e-mail.",
        'faq_q2': 'Puis-je retourner ou échanger ma commande ?',
        'faq_a2': "Oui, vous disposez de 30 jours à compter de la réception pour retourner tout article sans justification. Le retour est gratuit : écrivez à hola@isabellabcn.com et nous vous enverrons une étiquette prépayée. Le remboursement intervient sous 3–5 jours ouvrables.",
        'faq_q3': 'Quels matériaux utilisez-vous dans vos bijoux ?',
        'faq_a3': "Nous utilisons exclusivement des matériaux hypoallergéniques de haute qualité : argent sterling 925, acier inoxydable 316L et plaqué or 14k ou or rose. Sans nickel ni plomb. Toutes les pierres sont des zircons de haute qualité, résistants à l'eau.",
        'faq_q4': 'Comment choisir ma taille de bague ?',
        'faq_a4': "Mesurez le diamètre intérieur d'une bague qui vous va : taille 48 = 15,3 mm · 50 = 15,9 mm · 52 = 16,5 mm · 54 = 17,2 mm. En cas de doute, choisissez la taille supérieure. Beaucoup de nos bagues sont ajustables.",
        'faq_q5': 'Quels modes de paiement acceptez-vous ?',
        'faq_a5': "Nous acceptons les cartes de crédit et de débit (Visa, Mastercard, Amex) et PayPal. Les paiements par carte sont traités via Stripe avec chiffrement SSL. Nous ne stockons aucune donnée bancaire sur nos serveurs.",
        'faq_q6': 'Comment entretenir mes bijoux ?',
        'faq_a6': "1) Rangez-les dans la boîte fournie pour éviter les rayures. 2) Évitez le contact avec les parfums et crèmes — mettez-les en dernier. 3) Nettoyez avec un chiffon doux et sec. 4) Bien que résistants à l'eau, retirez-les avant de nager en mer ou en piscine.",

        'coleccion_sub':      'Isabella Barcelona · 2026',
        'sort_newest':        'Nouveautés',
        'sort_price_asc':     'Prix ↑',
        'sort_price_desc':    'Prix ↓',
        'product_singular':   'produit',
        'product_plural':     'produits',
        'col_empty_title':    'Aucun produit dans cette catégorie',
        'col_empty_text':     'Essayez une autre catégorie ou explorez toute la collection.',
        'col_empty_cta':      'Tout voir',

        'cart_title':         'Votre Panier',
        'cart_update':        'Mettre à jour',
        'cart_remove':        '✕ Supprimer',
        'cart_continue':      '← Continuer les achats',
        'cart_summary':       'RÉSUMÉ DE LA COMMANDE',
        'cart_subtotal':      'Sous-total',
        'cart_shipping':      'Livraison',
        'cart_free':          'Gratuit',
        'cart_calculated':    'Calculé à la caisse',
        'cart_total':         'Total',
        'cart_free_label':    'Livraison gratuite',
        'cart_free_pre':      'Ajoutez ',
        'cart_free_post':     ' de plus pour la livraison gratuite !',
        'cart_free_applied':  'Livraison gratuite appliquée !',
        'cart_checkout':      'Finaliser la commande',
        'cart_secure':        'Paiement sécurisé',
        'cart_returns':       'Retours gratuits',
        'cart_empty_title':   'Votre panier est vide',
        'cart_empty_text':    'Découvrez notre collection et trouvez le bijou parfait pour vous.',
        'cart_empty_cta':     'Voir la collection',

        'ck_bc_cart':         'Panier',
        'ck_bc_payment':      'Paiement',
        'ck_contact':         'Coordonnées',
        'ck_fullname':        'Nom complet *',
        'ck_phone':           'Téléphone',
        'ck_address':         'Adresse de livraison',
        'ck_street':          'Rue et numéro *',
        'ck_city':            'Ville *',
        'ck_postal':          'Code postal *',
        'ck_country':         'Pays *',
        'ck_payment_method':  'Mode de paiement',
        'ck_card':            'Carte de crédit',
        'ck_card_sub':        'Visa · Mastercard · Amex',
        'ck_paypal_sub':      'Paiement rapide et sécurisé',
        'ck_card_number':     'Numéro de carte',
        'ck_expiry':          'Expiration',
        'ck_cvv':             'CVV',
        'ck_ssl':             'Paiement sécurisé avec chiffrement SSL. Vos données bancaires ne sont pas stockées sur nos serveurs.',
        'ck_paypal_redirect': 'En confirmant votre commande, vous serez redirigée vers PayPal pour finaliser le paiement en toute sécurité.',
        'ck_submit':          'Confirmer la commande',
        'ck_terms':           'En confirmant, vous acceptez nos',
        'ck_terms_link1':     'Conditions de vente',
        'ck_terms_link2':     'Politique de retour',
        'ck_qty_label':       'Qté :',
        'ck_add_free_pre':    'Ajoutez ',
        'ck_add_free_post':   ' de plus pour la livraison gratuite',
        'ck_delivery_est':    'Livraison estimée : 5–8 jours ouvrables',
        'ck_returns30':       'Retour gratuit sous 30 jours',
        'ck_secure_pay':      'Paiement 100% sécurisé',
        'ck_back_cart':       '← Retour au panier',

        'ty_confirmed':    'COMMANDE CONFIRMÉE',
        'ty_title':        'Merci pour votre commande !',
        'ty_text':         'Nous avons bien reçu votre commande et la préparons avec soin. Vous recevrez un e-mail de confirmation sous peu.',
        'ty_order_number': 'NUMÉRO DE COMMANDE',
        'ty_detail':       'DÉTAIL DE LA COMMANDE',
        'ty_qty_label':    'Qté :',
        'ty_subtotal':     'Sous-total',
        'ty_shipping':     'Livraison',
        'ty_free':         'Gratuit',
        'ty_total':        'Total',
        'ty_ship_addr':    'ADRESSE DE LIVRAISON',
        'ty_delivery':     'Livraison estimée sous 5–8 jours ouvrables. Vous recevrez votre numéro de suivi par e-mail.',
        'ty_continue':     'Continuer les achats',
        'ty_my_orders':    'Mes commandes',
        'ty_sign':         'Avec amour, Isabella',

        'pd_sale':              'PROMO',
        'pd_enlarge':           'Agrandir',
        'pd_units_pre':         'Plus que ',
        'pd_units_post':        ' en stock !',
        'pd_in_stock_pre':      '✓ En stock — ',
        'pd_in_stock_post':     ' disponibles',
        'pd_out_stock':         '✗ Rupture de stock',
        'pd_qty_label':         'QUANTITÉ',
        'pd_add_cart':          'Ajouter au panier',
        'pd_no_stock_btn':      'Rupture de stock',
        'pd_free_ship':         'Livraison gratuite à partir de €100',
        'pd_secure':            'Paiement 100% sécurisé — Stripe & PayPal',
        'pd_returns':           'Retour gratuit sous 30 jours',
        'pd_reviews_rating':    '4.9/5 — plus de 2 000 avis vérifiés',
        'pd_acc_details':       'Détails du produit',
        'pd_acc_details_dflt':  "Bijou de haute qualité fabriqué avec des matériaux premium. Plaqué or 18K, hypoallergénique et résistant à l'eau.",
        'pd_acc_quality':       'Qualité',
        'pd_acc_quality_text':  "Nous offrons une garantie de 365 jours sur chaque bijou. Nos bijoux ne se décolorent pas. Pour les conserver plus longtemps, nous recommandons d'éviter le contact avec l'eau.",
        'pd_acc_tips':          "Conseils d'entretien",
        'pd_acc_tips_text':     "Gardez toujours vos bijoux hors de portée des enfants. Retirez-les sous la douche, pendant le sommeil, au sauna ou lors d'activités sportives.",
        'pd_related':           'Vous aimerez aussi',
        'pd_sp_ago':            'Il y a quelques minutes · Isabella Barcelona',
        'pd_sp_from':           'de',
        'pd_sp_bought':         "vient d'acheter ce produit",

        'login_welcome':     'BIENVENUE',
        'login_title':       'Se connecter',
        'login_user_label':  "NOM D'UTILISATEUR OU EMAIL",
        'login_pass_label':  'MOT DE PASSE',
        'login_btn':         'Connexion',
        'login_no_account':  'Pas encore de compte ?',
        'login_create':      'CRÉER UN COMPTE',

        'reg_label':         'REJOIGNEZ-NOUS',
        'reg_title':         'Créer un compte',
        'reg_subtitle':      'Rejoignez la famille Isabella Barcelona',
        'reg_username':      "NOM D'UTILISATEUR",
        'reg_pass':          'MOT DE PASSE',
        'reg_pass_confirm':  'CONFIRMER LE MOT DE PASSE',
        'reg_btn':           'Créer un compte',
        'reg_terms':         'En créant un compte, vous acceptez nos',
        'reg_terms_link1':   'Conditions de vente',
        'reg_terms_link2':   'Politique de confidentialité',
        'reg_have_account':  'Vous avez déjà un compte ?',
        'reg_login_link':    'SE CONNECTER',

        'account_label':         'MON COMPTE',
        'account_hello':         'Bonjour,',
        'account_logout_btn':    'DÉCONNEXION',
        'account_stat_orders':   'COMMANDES',
        'account_stat_shipped':  'EXPÉDIÉES',
        'account_stat_member':   'Membre',
        'account_stat_family':   'ISABELLA FAMILY',
        'account_my_orders':     'MES COMMANDES',
        'table_order':           'COMMANDE',
        'table_date':            'DATE',
        'table_status':          'STATUT',
        'table_total':           'TOTAL',
        'status_pending':        'EN ATTENTE',
        'status_paid':           'PAYÉE',
        'status_shipped':        'EXPÉDIÉE',
        'status_delivered':      'LIVRÉE',
        'status_cancelled':      'ANNULÉE',
        'account_no_orders':     "Pas encore de commandes",
        'account_no_orders_txt': 'Découvrez notre collection et trouvez votre premier bijou.',
        'account_explore':       'Voir la collection',

        # ── Footer ───────────────────────────────────────────────────────────
        'footer_newsletter_title': 'REJOIGNEZ LA FAMILLE',
        'footer_newsletter_text':  'Recevez en avant-première nos nouvelles collections et nos offres exclusives.',
        'footer_newsletter_ph':    'Votre adresse e-mail',
        'footer_mission_title':    'NOTRE MISSION',
        'footer_mission_text':     "Isabella Barcelona est née d'une idée simple — que chaque femme mérite de porter quelque chose de beau chaque jour.",
        'footer_mission_sign':     'Avec amour, Isabella',
        'footer_info_title':       'INFORMATION',
        'footer_faq_link':         'Questions fréquentes',
        'footer_story_link':       'Notre Histoire',
        'footer_legal_link':       'Mentions légales',
        'footer_terms_link':       'Conditions de vente',
        'footer_returns_link':     'Politique de retour',
        'footer_service_title':    'SERVICE CLIENT',
        'footer_service_text1':    "Vous avez une question ou besoin d'aide ?",
        'footer_service_text2':    'Notre équipe est là pour vous accompagner.',
        'footer_hours':            'Lundi – Vendredi : 10:00 – 18:00',
        'footer_copyright':        '© 2026 Isabella Barcelona · Tous droits réservés',

        # ── Exit popup ────────────────────────────────────────────────────────
        'exit_tagline':       'Ne partez pas encore',
        'exit_title':         'Attendez ! Votre panier<br>vous attend',
        'exit_text':          'En cadeau spécial, utilisez ce code exclusif et bénéficiez de 10% de réduction :',
        'exit_code_label':    'Votre code exclusif',
        'exit_discount_txt':  '10% de réduction sur votre commande',
        'exit_cta':           'Je veux ma réduction →',
        'exit_dismiss':       'Non merci — je préfère payer plus cher',
    },

    'de': {
        # ── Navbar ──────────────────────────────────────────────────────────
        'nav_inicio':     'Startseite',
        'nav_coleccion':  'Kollektion',
        'nav_pendientes': 'Ohrringe',
        'nav_collares':   'Halsketten',
        'nav_anillos':    'Ringe',
        'nav_brazaletes': 'Armbänder',
        'nav_carrito':    'Warenkorb',
        'nav_mi_cuenta':  'Mein Konto',
        'nav_salir':      'Abmelden',
        'nav_login':      'Anmelden',
        'nav_register':   'Registrieren',
        'nav_cerrar':     'Abmelden',
        'mob_menu':       'Menü',
        'mob_cats':       'Kategorien',

        'school_disclaimer': '⚠️ Hinweis: Diese Website ist ein Schulprojekt — kein echter Shop. Bestellungen werden nicht verarbeitet.',

        'ann_msg1': 'Kostenloser Versand ab €100',
        'ann_msg2': 'Begrenztes Angebot — bis zu -50%',
        'ann_msg3': '+2.000 zufriedene Kundinnen · Bewertung 4.9',

        'hero_new_collection': 'Neue Kollektion 2026',
        'hero_tagline':        'Damenschmuck · Mediterrane Eleganz',
        'hero_cta':            'KOLLEKTION ENTDECKEN',

        'cats_title': 'Unsere Kategorien',
        'cats_sub':   'ENTDECKEN SIE UNSERE KOLLEKTION',
        'cat_all':    'Alle',

        'offer_label': 'BEGRENZTES ANGEBOT',
        'offer_text':  'Bis zu -50% auf die gesamte Kollektion',
        'time_hours':  'STD',
        'time_min':    'MIN',
        'time_seg':    'SEK',

        'bestsellers_title': 'Bestseller',
        'bestsellers_sub':   'UNSERE FAVORITEN',
        'sale_badge':        'SALE',
        'btn_add':           '＋ Hinzufügen',

        'story_label': 'UNSERE GESCHICHTE',
        'story_title': 'Was ich Ihnen noch nie erzählt habe',
        'story_p1':    'Vor einigen Jahren änderte sich etwas in meinem Leben. Mir wurde klar, dass jede Frau verdient, sich jeden Tag besonders zu fühlen — nicht nur bei großen Anlässen, sondern in den kleinen Momenten des Alltags.',
        'story_p2':    'Deshalb habe ich Isabella Barcelona gegründet. Jedes Stück ist sorgfältig ausgewählt, um Sie in Ihren wertvollen Momenten zu begleiten — vom Morgenkaffee bis zum Abendessen mit Freundinnen.',
        'story_p3':    'Das ist keine Marketingstrategie. Es ist einfach meine Art, Danke zu sagen — an jede von Ihnen, die mir ihr Vertrauen geschenkt hat.',
        'story_sign':  'Mit Liebe, Isabella',

        'reviews_title': 'Verifizierte Bewertungen',
        'reviews_sub':   'UNSERE KUNDINNEN',
        'reviews_count': '+2.000 verifizierte Bewertungen',

        'faq_label': 'HÄUFIGE FRAGEN',
        'faq_title': 'Haben Sie Fragen?',
        'faq_q1': 'Wie lange dauert die Lieferung und was kostet sie?',
        'faq_a1': 'Bestellungen werden innerhalb von 24–48 Werktagen aus Barcelona versandt. Die Lieferung nach Europa dauert 5–8 Werktage für €3,90. Ab €100 Bestellwert ist der Versand kostenlos. Sie erhalten eine Sendungsverfolgungsnummer per E-Mail.',
        'faq_q2': 'Kann ich meine Bestellung zurückgeben oder umtauschen?',
        'faq_a2': 'Ja, Sie haben 30 Tage ab Lieferung, um jeden Artikel ohne Begründung zurückzusenden. Die Rücksendung ist kostenlos — schreiben Sie an hola@isabellabcn.com. Die Erstattung erfolgt innerhalb von 3–5 Werktagen.',
        'faq_q3': 'Welche Materialien verwenden Sie für Ihren Schmuck?',
        'faq_a3': 'Wir verwenden ausschließlich hypoallergene, hochwertige Materialien: Sterlingsilber 925, Edelstahl 316L und vergoldet mit echtem 14k- oder Roségold. Kein Nickel, kein Blei. Alle Steine sind hochwertige Zirkonia.',
        'faq_q4': 'Wie finde ich meine Ringgröße?',
        'faq_a4': 'Messen Sie den Innendurchmesser eines Rings, der Ihnen passt: Größe 48 = 15,3 mm · 50 = 15,9 mm · 52 = 16,5 mm · 54 = 17,2 mm. Im Zweifelsfall wählen Sie die größere Größe. Viele unserer Ringe sind verstellbar.',
        'faq_q5': 'Welche Zahlungsmethoden akzeptieren Sie?',
        'faq_a5': 'Wir akzeptieren Kredit- und Debitkarten (Visa, Mastercard, Amex) und PayPal. Kartenzahlungen werden über Stripe mit SSL-Verschlüsselung verarbeitet. Wir speichern keine Bankdaten auf unseren Servern.',
        'faq_q6': 'Wie pflege ich meinen Schmuck richtig?',
        'faq_a6': '1) Bewahren Sie ihn in der mitgelieferten Box auf. 2) Kontakt mit Parfüm und Cremes vermeiden — immer zuletzt anlegen. 3) Mit einem weichen, trockenen Tuch reinigen. 4) Vor dem Schwimmen im Meer oder Chlorwasser abnehmen.',

        'coleccion_sub':      'Isabella Barcelona · 2026',
        'sort_newest':        'Neuheiten',
        'sort_price_asc':     'Preis ↑',
        'sort_price_desc':    'Preis ↓',
        'product_singular':   'Produkt',
        'product_plural':     'Produkte',
        'col_empty_title':    'Keine Produkte in dieser Kategorie',
        'col_empty_text':     'Versuchen Sie eine andere Kategorie oder entdecken Sie die gesamte Kollektion.',
        'col_empty_cta':      'Alles ansehen',

        'cart_title':         'Ihr Warenkorb',
        'cart_update':        'Aktualisieren',
        'cart_remove':        '✕ Entfernen',
        'cart_continue':      '← Weiter einkaufen',
        'cart_summary':       'BESTELLÜBERSICHT',
        'cart_subtotal':      'Zwischensumme',
        'cart_shipping':      'Versand',
        'cart_free':          'Kostenlos',
        'cart_calculated':    'Wird beim Bezahlen berechnet',
        'cart_total':         'Gesamt',
        'cart_free_label':    'Kostenloser Versand',
        'cart_free_pre':      'Fügen Sie ',
        'cart_free_post':     ' hinzu für kostenlosen Versand!',
        'cart_free_applied':  'Kostenloser Versand aktiviert!',
        'cart_checkout':      'Zur Kasse',
        'cart_secure':        'Sicheres Bezahlen',
        'cart_returns':       'Kostenlose Rücksendung',
        'cart_empty_title':   'Ihr Warenkorb ist leer',
        'cart_empty_text':    'Entdecken Sie unsere Kollektion und finden Sie Ihren perfekten Schmuck.',
        'cart_empty_cta':     'Kollektion ansehen',

        'ck_bc_cart':         'Warenkorb',
        'ck_bc_payment':      'Bezahlung',
        'ck_contact':         'Kontaktdaten',
        'ck_fullname':        'Vollständiger Name *',
        'ck_phone':           'Telefon',
        'ck_address':         'Lieferadresse',
        'ck_street':          'Straße und Hausnummer *',
        'ck_city':            'Stadt *',
        'ck_postal':          'Postleitzahl *',
        'ck_country':         'Land *',
        'ck_payment_method':  'Zahlungsmethode',
        'ck_card':            'Kreditkarte',
        'ck_card_sub':        'Visa · Mastercard · Amex',
        'ck_paypal_sub':      'Schnell und sicher bezahlen',
        'ck_card_number':     'Kartennummer',
        'ck_expiry':          'Ablaufdatum',
        'ck_cvv':             'CVV',
        'ck_ssl':             'Sichere Zahlung mit SSL-Verschlüsselung. Ihre Kartendaten werden nicht auf unseren Servern gespeichert.',
        'ck_paypal_redirect': 'Nach der Bestätigung werden Sie zu PayPal weitergeleitet, um die Zahlung sicher abzuschließen.',
        'ck_submit':          'Bestellung bestätigen',
        'ck_terms':           'Mit der Bestätigung akzeptieren Sie unsere',
        'ck_terms_link1':     'Verkaufsbedingungen',
        'ck_terms_link2':     'Rückgaberichtlinie',
        'ck_qty_label':       'Menge:',
        'ck_add_free_pre':    'Fügen Sie ',
        'ck_add_free_post':   ' hinzu für kostenlosen Versand',
        'ck_delivery_est':    'Voraussichtliche Lieferung: 5–8 Werktage',
        'ck_returns30':       'Kostenlose Rücksendung innerhalb von 30 Tagen',
        'ck_secure_pay':      '100% sichere Zahlung',
        'ck_back_cart':       '← Zurück zum Warenkorb',

        'ty_confirmed':    'BESTELLUNG BESTÄTIGT',
        'ty_title':        'Vielen Dank für Ihre Bestellung!',
        'ty_text':         'Wir haben Ihre Bestellung erhalten und bereiten sie mit viel Sorgfalt vor. Sie erhalten in Kürze eine Bestätigungs-E-Mail.',
        'ty_order_number': 'BESTELLNUMMER',
        'ty_detail':       'BESTELLDETAILS',
        'ty_qty_label':    'Menge:',
        'ty_subtotal':     'Zwischensumme',
        'ty_shipping':     'Versand',
        'ty_free':         'Kostenlos',
        'ty_total':        'Gesamt',
        'ty_ship_addr':    'LIEFERADRESSE',
        'ty_delivery':     'Voraussichtliche Lieferung in 5–8 Werktagen. Ihre Sendungsverfolgungsnummer erhalten Sie per E-Mail.',
        'ty_continue':     'Weiter einkaufen',
        'ty_my_orders':    'Meine Bestellungen',
        'ty_sign':         'Mit Liebe, Isabella',

        'pd_sale':              'SALE',
        'pd_enlarge':           'Vergrößern',
        'pd_units_pre':         'Nur noch ',
        'pd_units_post':        ' Stück verfügbar!',
        'pd_in_stock_pre':      '✓ Auf Lager — ',
        'pd_in_stock_post':     ' Stück verfügbar',
        'pd_out_stock':         '✗ Nicht vorrätig',
        'pd_qty_label':         'MENGE',
        'pd_add_cart':          'In den Warenkorb',
        'pd_no_stock_btn':      'Nicht vorrätig',
        'pd_free_ship':         'Kostenloser Versand ab €100',
        'pd_secure':            '100% sichere Zahlung — Stripe & PayPal',
        'pd_returns':           'Kostenlose Rücksendung innerhalb von 30 Tagen',
        'pd_reviews_rating':    '4.9/5 — über 2.000 verifizierte Bewertungen',
        'pd_acc_details':       'Produktdetails',
        'pd_acc_details_dflt':  'Hochwertiger Schmuck aus Premiummaterialien. 18K Vergoldung, hypoallergen und wasserbeständig.',
        'pd_acc_quality':       'Qualität',
        'pd_acc_quality_text':  'Wir bieten 365 Tage Garantie auf jeden Schmuck. Unser Schmuck verfärbt sich nicht. Um Ihren Schmuck länger schön zu halten, empfehlen wir, Kontakt mit Wasser zu vermeiden.',
        'pd_acc_tips':          'Pflegehinweise',
        'pd_acc_tips_text':     'Halten Sie Schmuck stets außer Reichweite von Kindern. Nehmen Sie Schmuck beim Duschen, Schlafen, in der Sauna oder beim Sport ab.',
        'pd_related':           'Das könnte Ihnen auch gefallen',
        'pd_sp_ago':            'Vor wenigen Minuten · Isabella Barcelona',
        'pd_sp_from':           'aus',
        'pd_sp_bought':         'hat dieses Produkt gerade gekauft',

        'login_welcome':     'WILLKOMMEN',
        'login_title':       'Anmelden',
        'login_user_label':  'BENUTZERNAME ODER E-MAIL',
        'login_pass_label':  'PASSWORT',
        'login_btn':         'Anmelden',
        'login_no_account':  'Noch kein Konto?',
        'login_create':      'KONTO ERSTELLEN',

        'reg_label':         'MITGLIED WERDEN',
        'reg_title':         'Konto erstellen',
        'reg_subtitle':      'Werden Sie Teil der Isabella Barcelona Familie',
        'reg_username':      'BENUTZERNAME',
        'reg_pass':          'PASSWORT',
        'reg_pass_confirm':  'PASSWORT BESTÄTIGEN',
        'reg_btn':           'Konto erstellen',
        'reg_terms':         'Mit der Erstellung eines Kontos akzeptieren Sie unsere',
        'reg_terms_link1':   'Verkaufsbedingungen',
        'reg_terms_link2':   'Datenschutzrichtlinie',
        'reg_have_account':  'Schon ein Konto?',
        'reg_login_link':    'ANMELDEN',

        'account_label':         'MEIN KONTO',
        'account_hello':         'Hallo,',
        'account_logout_btn':    'ABMELDEN',
        'account_stat_orders':   'BESTELLUNGEN',
        'account_stat_shipped':  'VERSENDET',
        'account_stat_member':   'Mitglied',
        'account_stat_family':   'ISABELLA FAMILY',
        'account_my_orders':     'MEINE BESTELLUNGEN',
        'table_order':           'BESTELLUNG',
        'table_date':            'DATUM',
        'table_status':          'STATUS',
        'table_total':           'GESAMT',
        'status_pending':        'AUSSTEHEND',
        'status_paid':           'BEZAHLT',
        'status_shipped':        'VERSENDET',
        'status_delivered':      'GELIEFERT',
        'status_cancelled':      'STORNIERT',
        'account_no_orders':     'Noch keine Bestellungen',
        'account_no_orders_txt': 'Entdecken Sie unsere Kollektion und finden Sie Ihren ersten Schmuck.',
        'account_explore':       'Kollektion ansehen',

        # ── Footer ───────────────────────────────────────────────────────────
        'footer_newsletter_title': 'WERDE TEIL DER FAMILIE',
        'footer_newsletter_text':  'Erhalten Sie als Erste unsere neuen Kollektionen und exklusiven Angebote.',
        'footer_newsletter_ph':    'Ihre E-Mail-Adresse',
        'footer_mission_title':    'UNSERE MISSION',
        'footer_mission_text':     'Isabella Barcelona entstand aus einer einfachen Idee — dass jede Frau es verdient, jeden Tag etwas Schönes zu tragen.',
        'footer_mission_sign':     'Mit Liebe, Isabella',
        'footer_info_title':       'INFORMATION',
        'footer_faq_link':         'Häufige Fragen',
        'footer_story_link':       'Unsere Geschichte',
        'footer_legal_link':       'Impressum',
        'footer_terms_link':       'Verkaufsbedingungen',
        'footer_returns_link':     'Rückgaberichtlinie',
        'footer_service_title':    'KUNDENDIENST',
        'footer_service_text1':    'Haben Sie eine Frage oder benötigen Sie Hilfe?',
        'footer_service_text2':    'Unser Team ist für Sie da.',
        'footer_hours':            'Montag – Freitag: 10:00 – 18:00 Uhr',
        'footer_copyright':        '© 2026 Isabella Barcelona · Alle Rechte vorbehalten',

        # ── Exit popup ────────────────────────────────────────────────────────
        'exit_tagline':       'Noch nicht gehen',
        'exit_title':         'Warten Sie! Ihr Warenkorb<br>wartet auf Sie',
        'exit_text':          'Als besonderes Geschenk: Nutzen Sie diesen exklusiven Code und erhalten Sie 10% Rabatt:',
        'exit_code_label':    'Ihr exklusiver Code',
        'exit_discount_txt':  '10% Rabatt auf Ihre Bestellung',
        'exit_cta':           'Ich möchte meinen Rabatt →',
        'exit_dismiss':       'Nein danke — ich zahle lieber mehr',
    },

    'it': {
        # ── Navbar ──────────────────────────────────────────────────────────
        'nav_inicio':     'Home',
        'nav_coleccion':  'Collezione',
        'nav_pendientes': 'Orecchini',
        'nav_collares':   'Collane',
        'nav_anillos':    'Anelli',
        'nav_brazaletes': 'Bracciali',
        'nav_carrito':    'Carrello',
        'nav_mi_cuenta':  'Il mio account',
        'nav_salir':      'Esci',
        'nav_login':      'Accedi',
        'nav_register':   'Registrati',
        'nav_cerrar':     'Esci',
        'mob_menu':       'Menu',
        'mob_cats':       'Categorie',

        'school_disclaimer': '⚠️ Avviso: Questo sito è un progetto scolastico — non è un vero negozio. Gli ordini non vengono elaborati.',

        'ann_msg1': 'Spedizione gratuita per ordini superiori a €100',
        'ann_msg2': 'Offerta limitata — fino al -50%',
        'ann_msg3': '+2.000 clienti soddisfatte · Valutazione 4.9',

        'hero_new_collection': 'Nuova Collezione 2026',
        'hero_tagline':        'Gioielli femminili · Eleganza mediterranea',
        'hero_cta':            'SCOPRI LA COLLEZIONE',

        'cats_title': 'Le Nostre Categorie',
        'cats_sub':   'SCOPRI LA NOSTRA COLLEZIONE',
        'cat_all':    'Tutto',

        'offer_label': 'OFFERTA LIMITATA',
        'offer_text':  'Fino al -50% su tutta la collezione',
        'time_hours':  'ORE',
        'time_min':    'MIN',
        'time_seg':    'SEC',

        'bestsellers_title': 'Più Venduti',
        'bestsellers_sub':   'I NOSTRI PREFERITI',
        'sale_badge':        'OFFERTA',
        'btn_add':           '＋ Aggiungi',

        'story_label': 'LA NOSTRA STORIA',
        'story_title': 'Quello che non ti ho mai detto',
        'story_p1':    'Qualche anno fa, qualcosa è cambiato nella mia vita. Mi sono resa conto che ogni donna merita di sentirsi speciale ogni giorno — non solo nelle grandi occasioni, ma nei piccoli momenti della vita quotidiana.',
        'story_p2':    'Per questo ho deciso di creare Isabella Barcelona. Ogni pezzo è scelto con cura, per accompagnarti nei tuoi momenti preziosi — dal caffè mattutino alla cena con le amiche.',
        'story_p3':    'Questa non è una strategia di marketing. È semplicemente il mio modo di dire grazie — a ognuna di voi che mi ha dato la propria fiducia.',
        'story_sign':  'Con amore, Isabella',

        'reviews_title': 'Recensioni Verificate',
        'reviews_sub':   'LE NOSTRE CLIENTI',
        'reviews_count': '+2.000 recensioni verificate',

        'faq_label': 'DOMANDE FREQUENTI',
        'faq_title': 'Hai delle domande?',
        'faq_q1': 'Quanto tempo richiede la spedizione e quanto costa?',
        'faq_a1': 'Gli ordini vengono spediti entro 24–48 ore lavorative da Barcellona. La consegna standard in Europa richiede 5–8 giorni lavorativi per €3,90. Spedizione gratuita per ordini superiori a €100. Riceverai un numero di tracciamento via e-mail.',
        'faq_q2': 'Posso restituire o cambiare il mio ordine?',
        'faq_a2': "Sì, hai 30 giorni dalla consegna per restituire qualsiasi articolo senza motivazione. Il reso è gratuito — scrivi a hola@isabellabcn.com e ti invieremo un'etichetta prepagata. Il rimborso avviene entro 3–5 giorni lavorativi.",
        'faq_q3': 'Quali materiali utilizzate per i vostri gioielli?',
        'faq_a3': 'Utilizziamo esclusivamente materiali ipoallergenici di alta qualità: argento sterling 925, acciaio inossidabile 316L e placcato oro 14k o oro rosa. Senza nichel né piombo. Tutte le pietre sono zirconi di alta qualità.',
        'faq_q4': 'Come scelgo la mia taglia di anello?',
        'faq_a4': 'Misura il diametro interno di un anello che ti va bene: misura 48 = 15,3 mm · 50 = 15,9 mm · 52 = 16,5 mm · 54 = 17,2 mm. Se sei tra due misure, scegli la più grande. Molti dei nostri anelli sono regolabili.',
        'faq_q5': 'Quali metodi di pagamento accettate?',
        'faq_a5': 'Accettiamo carte di credito e di debito (Visa, Mastercard, Amex) e PayPal. I pagamenti con carta vengono elaborati tramite Stripe con crittografia SSL. Non conserviamo dati bancari sui nostri server.',
        'faq_q6': 'Come curo correttamente i miei gioielli?',
        'faq_a6': "1) Conservali nella scatola fornita per evitare graffi. 2) Evita il contatto con profumi e creme — indossali per ultimi. 3) Pulisci con un panno morbido e asciutto. 4) Anche se resistenti all'acqua, toglili prima di nuotare in mare o in piscina con cloro.",

        'coleccion_sub':      'Isabella Barcelona · 2026',
        'sort_newest':        'Novità',
        'sort_price_asc':     'Prezzo ↑',
        'sort_price_desc':    'Prezzo ↓',
        'product_singular':   'prodotto',
        'product_plural':     'prodotti',
        'col_empty_title':    'Nessun prodotto in questa categoria',
        'col_empty_text':     "Prova un'altra categoria o esplora tutta la collezione.",
        'col_empty_cta':      'Vedi tutto',

        'cart_title':         'Il tuo Carrello',
        'cart_update':        'Aggiorna',
        'cart_remove':        '✕ Rimuovi',
        'cart_continue':      '← Continua gli acquisti',
        'cart_summary':       "RIEPILOGO DELL'ORDINE",
        'cart_subtotal':      'Subtotale',
        'cart_shipping':      'Spedizione',
        'cart_free':          'Gratuita',
        'cart_calculated':    'Calcolata al pagamento',
        'cart_total':         'Totale',
        'cart_free_label':    'Spedizione gratuita',
        'cart_free_pre':      'Aggiungi ',
        'cart_free_post':     ' per la spedizione gratuita!',
        'cart_free_applied':  'Spedizione gratuita applicata!',
        'cart_checkout':      'Procedi al pagamento',
        'cart_secure':        'Pagamento sicuro',
        'cart_returns':       'Resi gratuiti',
        'cart_empty_title':   'Il tuo carrello è vuoto',
        'cart_empty_text':    'Scopri la nostra collezione e trova il gioiello perfetto per te.',
        'cart_empty_cta':     'Vedi la collezione',

        'ck_bc_cart':         'Carrello',
        'ck_bc_payment':      'Pagamento',
        'ck_contact':         'Dati di contatto',
        'ck_fullname':        'Nome completo *',
        'ck_phone':           'Telefono',
        'ck_address':         'Indirizzo di spedizione',
        'ck_street':          'Via e numero civico *',
        'ck_city':            'Città *',
        'ck_postal':          'Codice postale *',
        'ck_country':         'Paese *',
        'ck_payment_method':  'Metodo di pagamento',
        'ck_card':            'Carta di credito',
        'ck_card_sub':        'Visa · Mastercard · Amex',
        'ck_paypal_sub':      'Pagamento rapido e sicuro',
        'ck_card_number':     'Numero di carta',
        'ck_expiry':          'Scadenza',
        'ck_cvv':             'CVV',
        'ck_ssl':             'Pagamento sicuro con crittografia SSL. I dati della tua carta non vengono conservati sui nostri server.',
        'ck_paypal_redirect': "Confermando l'ordine verrai reindirizzata a PayPal per completare il pagamento in sicurezza.",
        'ck_submit':          "Conferma l'ordine",
        'ck_terms':           'Confermando, accetti i nostri',
        'ck_terms_link1':     'Termini di vendita',
        'ck_terms_link2':     'Politica di reso',
        'ck_qty_label':       'Qtà:',
        'ck_add_free_pre':    'Aggiungi ',
        'ck_add_free_post':   ' per la spedizione gratuita',
        'ck_delivery_est':    'Consegna stimata: 5–8 giorni lavorativi',
        'ck_returns30':       'Reso gratuito entro 30 giorni',
        'ck_secure_pay':      'Pagamento 100% sicuro',
        'ck_back_cart':       '← Torna al carrello',

        'ty_confirmed':    'ORDINE CONFERMATO',
        'ty_title':        'Grazie per il tuo ordine!',
        'ty_text':         "Abbiamo ricevuto il tuo ordine e lo stiamo preparando con cura. Riceverai un'e-mail di conferma a breve.",
        'ty_order_number': "NUMERO D'ORDINE",
        'ty_detail':       "DETTAGLIO DELL'ORDINE",
        'ty_qty_label':    'Qtà:',
        'ty_subtotal':     'Subtotale',
        'ty_shipping':     'Spedizione',
        'ty_free':         'Gratuita',
        'ty_total':        'Totale',
        'ty_ship_addr':    'INDIRIZZO DI SPEDIZIONE',
        'ty_delivery':     'Consegna stimata in 5–8 giorni lavorativi. Ti invieremo il numero di tracciamento via e-mail.',
        'ty_continue':     'Continua gli acquisti',
        'ty_my_orders':    'I miei ordini',
        'ty_sign':         'Con amore, Isabella',

        'pd_sale':              'OFFERTA',
        'pd_enlarge':           'Ingrandisci',
        'pd_units_pre':         'Rimangono solo ',
        'pd_units_post':        ' pezzi!',
        'pd_in_stock_pre':      '✓ Disponibile — ',
        'pd_in_stock_post':     ' pezzi disponibili',
        'pd_out_stock':         '✗ Esaurito',
        'pd_qty_label':         'QUANTITÀ',
        'pd_add_cart':          'Aggiungi al carrello',
        'pd_no_stock_btn':      'Esaurito',
        'pd_free_ship':         'Spedizione gratuita per ordini superiori a €100',
        'pd_secure':            'Pagamento 100% sicuro — Stripe & PayPal',
        'pd_returns':           'Reso gratuito entro 30 giorni',
        'pd_reviews_rating':    '4.9/5 — oltre 2.000 recensioni verificate',
        'pd_acc_details':       'Dettagli del prodotto',
        'pd_acc_details_dflt':  "Gioiello di alta qualità realizzato con materiali premium. Placcato oro 18K, ipoallergenico e resistente all'acqua.",
        'pd_acc_quality':       'Qualità',
        'pd_acc_quality_text':  "Offriamo 365 giorni di garanzia su ogni gioiello. I nostri gioielli non si scoloriscono. Per mantenerli belli più a lungo, consigliamo di evitare il contatto con l'acqua.",
        'pd_acc_tips':          'Consigli per la cura',
        'pd_acc_tips_text':     'Tieni sempre i tuoi gioielli fuori dalla portata dei bambini. Rimuovili quando fai la doccia, dormi, vai in sauna o fai sport.',
        'pd_related':           'Potrebbe piacerti anche',
        'pd_sp_ago':            'Pochi minuti fa · Isabella Barcelona',
        'pd_sp_from':           'di',
        'pd_sp_bought':         'ha appena acquistato questo prodotto',

        'login_welcome':     'BENVENUTA',
        'login_title':       'Accedi',
        'login_user_label':  'NOME UTENTE O EMAIL',
        'login_pass_label':  'PASSWORD',
        'login_btn':         'Accedi',
        'login_no_account':  'Non hai ancora un account?',
        'login_create':      'CREA ACCOUNT',

        'reg_label':         'UNISCITI A NOI',
        'reg_title':         'Crea Account',
        'reg_subtitle':      'Entra a far parte della famiglia Isabella Barcelona',
        'reg_username':      'NOME UTENTE',
        'reg_pass':          'PASSWORD',
        'reg_pass_confirm':  'CONFERMA PASSWORD',
        'reg_btn':           'Crea Account',
        'reg_terms':         'Creando un account accetti i nostri',
        'reg_terms_link1':   'Termini di vendita',
        'reg_terms_link2':   'Informativa sulla privacy',
        'reg_have_account':  'Hai già un account?',
        'reg_login_link':    'ACCEDI',

        'account_label':         'IL MIO ACCOUNT',
        'account_hello':         'Ciao,',
        'account_logout_btn':    'ESCI',
        'account_stat_orders':   'ORDINI',
        'account_stat_shipped':  'SPEDITI',
        'account_stat_member':   'Membro',
        'account_stat_family':   'ISABELLA FAMILY',
        'account_my_orders':     'I MIEI ORDINI',
        'table_order':           'ORDINE',
        'table_date':            'DATA',
        'table_status':          'STATO',
        'table_total':           'TOTALE',
        'status_pending':        'IN ATTESA',
        'status_paid':           'PAGATO',
        'status_shipped':        'SPEDITO',
        'status_delivered':      'CONSEGNATO',
        'status_cancelled':      'ANNULLATO',
        'account_no_orders':     'Ancora nessun ordine',
        'account_no_orders_txt': 'Scopri la nostra collezione e trova il tuo primo gioiello.',
        'account_explore':       'Vedi la collezione',

        # ── Footer ───────────────────────────────────────────────────────────
        'footer_newsletter_title': 'UNISCITI ALLA FAMIGLIA',
        'footer_newsletter_text':  'Ricevi in anteprima le nostre nuove collezioni e le offerte esclusive.',
        'footer_newsletter_ph':    'Il tuo indirizzo e-mail',
        'footer_mission_title':    'LA NOSTRA MISSIONE',
        'footer_mission_text':     "Isabella Barcelona è nata da un'idea semplice — che ogni donna meriti di indossare qualcosa di bello ogni giorno.",
        'footer_mission_sign':     'Con amore, Isabella',
        'footer_info_title':       'INFORMAZIONI',
        'footer_faq_link':         'Domande frequenti',
        'footer_story_link':       'La Nostra Storia',
        'footer_legal_link':       'Note legali',
        'footer_terms_link':       'Condizioni di vendita',
        'footer_returns_link':     'Politica di reso',
        'footer_service_title':    'SERVIZIO CLIENTI',
        'footer_service_text1':    'Hai una domanda o hai bisogno di aiuto?',
        'footer_service_text2':    'Il nostro team è qui per te.',
        'footer_hours':            'Lunedì – Venerdì: 10:00 – 18:00',
        'footer_copyright':        '© 2026 Isabella Barcelona · Tutti i diritti riservati',

        # ── Exit popup ────────────────────────────────────────────────────────
        'exit_tagline':       'Non andare ancora',
        'exit_title':         'Aspetta! Il tuo carrello<br>ti sta aspettando',
        'exit_text':          'Come regalo speciale, usa questo codice esclusivo e ottieni il 10% di sconto:',
        'exit_code_label':    'Il tuo codice esclusivo',
        'exit_discount_txt':  '10% di sconto sul tuo ordine',
        'exit_cta':           'Voglio il mio sconto →',
        'exit_dismiss':       'No grazie — preferisco pagare di più',
    },

    'cs': {
        # ── Navbar ──────────────────────────────────────────────────────────
        'nav_inicio':     'Úvod',
        'nav_coleccion':  'Kolekce',
        'nav_pendientes': 'Náušnice',
        'nav_collares':   'Náhrdelníky',
        'nav_anillos':    'Prsteny',
        'nav_brazaletes': 'Náramky',
        'nav_carrito':    'Košík',
        'nav_mi_cuenta':  'Můj účet',
        'nav_salir':      'Odhlásit',
        'nav_login':      'Přihlásit se',
        'nav_register':   'Registrovat se',
        'nav_cerrar':     'Odhlásit se',
        'mob_menu':       'Menu',
        'mob_cats':       'Kategorie',

        'school_disclaimer': '⚠️ Tento web je školní projekt — nejde o skutečný e-shop. Objednávky nejsou zpracovávány.',

        'ann_msg1': 'Doprava zdarma při nákupu nad €100',
        'ann_msg2': 'Omezená nabídka — až -50%',
        'ann_msg3': '+2 000 spokojených zákaznic · Hodnocení 4.9',

        'hero_new_collection': 'Nová Kolekce 2026',
        'hero_tagline':        'Dámské šperky · Středomořská elegance',
        'hero_cta':            'ZOBRAZIT KOLEKCI',

        'cats_title': 'Naše Kategorie',
        'cats_sub':   'OBJEVTE NAŠI KOLEKCI',
        'cat_all':    'Vše',

        'offer_label': 'OMEZENÁ NABÍDKA',
        'offer_text':  'Až -50% na celou kolekci',
        'time_hours':  'HOD',
        'time_min':    'MIN',
        'time_seg':    'SEK',

        'bestsellers_title': 'Nejprodávanější',
        'bestsellers_sub':   'NAŠE OBLÍBENÉ',
        'sale_badge':        'SLEVA',
        'btn_add':           '＋ Přidat',

        'story_label': 'NÁŠ PŘÍBĚH',
        'story_title': 'Co jsem vám nikdy neřekla',
        'story_p1':    'Před několika lety se něco změnilo v mém životě. Uvědomila jsem si, že každá žena si zaslouží cítit se výjimečně každý den — nejen při velkých příležitostech, ale v malých okamžicích každodenního života.',
        'story_p2':    'Proto jsem se rozhodla vytvořit Isabella Barcelona. Každý kousek je pečlivě vybrán, aby vás doprovázel ve vašich vzácných chvílích — od ranní kávy po večeři s přáteli.',
        'story_p3':    'To není marketingová strategie. Je to jednoduše můj způsob, jak vám říci díky — každé z vás, která mi dala svou důvěru.',
        'story_sign':  'S láskou, Isabella',

        'reviews_title': 'Ověřené Recenze',
        'reviews_sub':   'NAŠE ZÁKAZNICE',
        'reviews_count': '+2 000 ověřených recenzí',

        'faq_label': 'ČASTÉ DOTAZY',
        'faq_title': 'Máte otázky?',
        'faq_q1': 'Jak dlouho trvá doručení a kolik stojí?',
        'faq_a1': 'Objednávky odesíláme do 24–48 pracovních hodin z Barcelony. Standardní doručení do Evropy trvá 5–8 pracovních dnů za €3,90. Při nákupu nad €100 je doprava zdarma. Sledovací číslo obdržíte e-mailem.',
        'faq_q2': 'Mohu vrátit nebo vyměnit objednávku?',
        'faq_a2': 'Ano, máte 30 dní od doručení na vrácení zboží bez udání důvodu. Vrácení je zdarma — napište na hola@isabellabcn.com a zašleme vám předplacenou štítek. Refundace proběhne do 3–5 pracovních dnů.',
        'faq_q3': 'Jaké materiály používáte ve svých špercích?',
        'faq_a3': 'Používáme výhradně hypoalergenní materiály vysoké kvality: stříbro 925, nerezová ocel 316L a pozlacení 14k zlatem nebo růžovým zlatem. Bez niklu a olova. Kameny jsou vysoce kvalitní zirkonie odolné vodě.',
        'faq_q4': 'Jak zjistím svou velikost prstenu?',
        'faq_a4': 'Změřte vnitřní průměr prstenu, který vám sedí: velikost 48 = 15,3 mm · 50 = 15,9 mm · 52 = 16,5 mm · 54 = 17,2 mm. Pokud jste mezi velikostmi, zvolte větší. Mnoho našich prstenů je nastavitelných.',
        'faq_q5': 'Jaké způsoby platby přijímáte?',
        'faq_a5': 'Přijímáme kreditní a debetní karty (Visa, Mastercard, Amex) a PayPal. Platby kartou jsou zpracovávány přes Stripe s SSL šifrováním. Na našich serverech neukládáme žádné bankovní údaje.',
        'faq_q6': 'Jak správně pečovat o šperky?',
        'faq_a6': '1) Ukládejte je v přiložené krabičce, aby nedocházelo k poškrábání. 2) Vyhýbejte se kontaktu s parfémy a krémy — nasazujte je jako poslední. 3) Čistěte měkkým suchým hadříkem. 4) Před plaváním v moři nebo bazénu je sundejte.',

        'coleccion_sub':      'Isabella Barcelona · 2026',
        'sort_newest':        'Novinky',
        'sort_price_asc':     'Cena ↑',
        'sort_price_desc':    'Cena ↓',
        'product_singular':   'produkt',
        'product_plural':     'produkty',
        'col_empty_title':    'V této kategorii nejsou žádné produkty',
        'col_empty_text':     'Zkuste jinou kategorii nebo prozkoumejte celou kolekci.',
        'col_empty_cta':      'Zobrazit vše',

        'cart_title':         'Váš košík',
        'cart_update':        'Aktualizovat',
        'cart_remove':        '✕ Odstranit',
        'cart_continue':      '← Pokračovat v nákupu',
        'cart_summary':       'PŘEHLED OBJEDNÁVKY',
        'cart_subtotal':      'Mezisoučet',
        'cart_shipping':      'Doprava',
        'cart_free':          'Zdarma',
        'cart_calculated':    'Vypočítáno při platbě',
        'cart_total':         'Celkem',
        'cart_free_label':    'Doprava zdarma',
        'cart_free_pre':      'Přidejte ještě ',
        'cart_free_post':     ' pro dopravu zdarma!',
        'cart_free_applied':  'Doprava zdarma aktivována!',
        'cart_checkout':      'Přejít k pokladně',
        'cart_secure':        'Zabezpečená platba',
        'cart_returns':       'Vrácení zdarma',
        'cart_empty_title':   'Váš košík je prázdný',
        'cart_empty_text':    'Prohlédněte si naši kolekci a najděte ideální šperk pro vás.',
        'cart_empty_cta':     'Zobrazit kolekci',

        'ck_bc_cart':         'Košík',
        'ck_bc_payment':      'Platba',
        'ck_contact':         'Kontaktní údaje',
        'ck_fullname':        'Celé jméno *',
        'ck_phone':           'Telefon',
        'ck_address':         'Doručovací adresa',
        'ck_street':          'Ulice a číslo popisné *',
        'ck_city':            'Město *',
        'ck_postal':          'PSČ *',
        'ck_country':         'Země *',
        'ck_payment_method':  'Způsob platby',
        'ck_card':            'Kreditní karta',
        'ck_card_sub':        'Visa · Mastercard · Amex',
        'ck_paypal_sub':      'Rychlá a bezpečná platba',
        'ck_card_number':     'Číslo karty',
        'ck_expiry':          'Platnost',
        'ck_cvv':             'CVV',
        'ck_ssl':             'Bezpečná platba s SSL šifrováním. Údaje vaší karty nejsou ukládány na našich serverech.',
        'ck_paypal_redirect': 'Po potvrzení objednávky budete přesměrováni na PayPal k dokončení platby.',
        'ck_submit':          'Potvrdit objednávku',
        'ck_terms':           'Potvrzením souhlasíte s našimi',
        'ck_terms_link1':     'Obchodními podmínkami',
        'ck_terms_link2':     'Zásadami vrácení',
        'ck_qty_label':       'Ks:',
        'ck_add_free_pre':    'Přidejte ještě ',
        'ck_add_free_post':   ' pro dopravu zdarma',
        'ck_delivery_est':    'Odhadovaná doručení: 5–8 pracovních dnů',
        'ck_returns30':       'Vrácení zdarma do 30 dnů',
        'ck_secure_pay':      '100% bezpečná platba',
        'ck_back_cart':       '← Zpět do košíku',

        'ty_confirmed':    'OBJEDNÁVKA POTVRZENA',
        'ty_title':        'Děkujeme za vaši objednávku!',
        'ty_text':         'Obdrželi jsme vaši objednávku a pečlivě ji připravujeme. Potvrzovací e-mail vám bude odeslán co nejdříve.',
        'ty_order_number': 'ČÍSLO OBJEDNÁVKY',
        'ty_detail':       'DETAIL OBJEDNÁVKY',
        'ty_qty_label':    'Ks:',
        'ty_subtotal':     'Mezisoučet',
        'ty_shipping':     'Doprava',
        'ty_free':         'Zdarma',
        'ty_total':        'Celkem',
        'ty_ship_addr':    'DORUČOVACÍ ADRESA',
        'ty_delivery':     'Odhadovaná doručení za 5–8 pracovních dnů. Sledovací číslo vám zašleme e-mailem.',
        'ty_continue':     'Pokračovat v nákupu',
        'ty_my_orders':    'Moje objednávky',
        'ty_sign':         'S láskou, Isabella',

        'pd_sale':              'SLEVA',
        'pd_enlarge':           'Zvětšit',
        'pd_units_pre':         'Zbývají pouze ',
        'pd_units_post':        ' kusy!',
        'pd_in_stock_pre':      '✓ Skladem — ',
        'pd_in_stock_post':     ' kusů k dispozici',
        'pd_out_stock':         '✗ Vyprodáno',
        'pd_qty_label':         'MNOŽSTVÍ',
        'pd_add_cart':          'Přidat do košíku',
        'pd_no_stock_btn':      'Vyprodáno',
        'pd_free_ship':         'Doprava zdarma při nákupu nad €100',
        'pd_secure':            '100% bezpečná platba — Stripe & PayPal',
        'pd_returns':           'Vrácení zdarma do 30 dnů',
        'pd_reviews_rating':    '4.9/5 — více než 2 000 ověřených recenzí',
        'pd_acc_details':       'Detaily produktu',
        'pd_acc_details_dflt':  'Vysoce kvalitní šperk z prémiových materiálů. Pozlacení 18K, hypoalergenní a voděodolný.',
        'pd_acc_quality':       'Kvalita',
        'pd_acc_quality_text':  'Nabízíme 365denní záruku na každý šperk. Naše šperky nevybarvují. Pro zachování krásy doporučujeme vyhýbat se kontaktu s vodou.',
        'pd_acc_tips':          'Rady pro péči',
        'pd_acc_tips_text':     'Vždy uchovávejte šperky mimo dosah dětí. Sundávejte je při sprchování, spaní, v sauně nebo při sportu.',
        'pd_related':           'Mohlo by se vám také líbit',
        'pd_sp_ago':            'Před několika minutami · Isabella Barcelona',
        'pd_sp_from':           'z',
        'pd_sp_bought':         'právě koupila tento produkt',

        'login_welcome':     'VÍTEJTE',
        'login_title':       'Přihlásit se',
        'login_user_label':  'UŽIVATELSKÉ JMÉNO NEBO E-MAIL',
        'login_pass_label':  'HESLO',
        'login_btn':         'Přihlásit',
        'login_no_account':  'Ještě nemáte účet?',
        'login_create':      'VYTVOŘIT ÚČET',

        'reg_label':         'PŘIDEJTE SE',
        'reg_title':         'Vytvořit účet',
        'reg_subtitle':      'Staňte se součástí rodiny Isabella Barcelona',
        'reg_username':      'UŽIVATELSKÉ JMÉNO',
        'reg_pass':          'HESLO',
        'reg_pass_confirm':  'POTVRDIT HESLO',
        'reg_btn':           'Vytvořit účet',
        'reg_terms':         'Vytvořením účtu souhlasíte s našimi',
        'reg_terms_link1':   'Obchodními podmínkami',
        'reg_terms_link2':   'Zásadami ochrany soukromí',
        'reg_have_account':  'Již máte účet?',
        'reg_login_link':    'PŘIHLÁSIT SE',

        'account_label':         'MŮJ ÚČET',
        'account_hello':         'Ahoj,',
        'account_logout_btn':    'ODHLÁSIT SE',
        'account_stat_orders':   'OBJEDNÁVKY',
        'account_stat_shipped':  'ODESLÁNO',
        'account_stat_member':   'Člen',
        'account_stat_family':   'ISABELLA FAMILY',
        'account_my_orders':     'MOJE OBJEDNÁVKY',
        'table_order':           'OBJEDNÁVKA',
        'table_date':            'DATUM',
        'table_status':          'STAV',
        'table_total':           'CELKEM',
        'status_pending':        'ČEKÁ NA ZPRACOVÁNÍ',
        'status_paid':           'ZAPLACENO',
        'status_shipped':        'ODESLÁNO',
        'status_delivered':      'DORUČENO',
        'status_cancelled':      'ZRUŠENO',
        'account_no_orders':     'Zatím žádné objednávky',
        'account_no_orders_txt': 'Prohlédněte si naši kolekci a najděte svůj první šperk.',
        'account_explore':       'Zobrazit kolekci',

        # ── Footer ───────────────────────────────────────────────────────────
        'footer_newsletter_title': 'PŘIDEJTE SE K RODINĚ',
        'footer_newsletter_text':  'Jako první získejte nové kolekce a exkluzivní nabídky.',
        'footer_newsletter_ph':    'Vaše e-mailová adresa',
        'footer_mission_title':    'NAŠE POSLÁNÍ',
        'footer_mission_text':     'Isabella Barcelona vznikla z jednoduché myšlenky — že každá žena si zaslouží každý den nosit něco krásného.',
        'footer_mission_sign':     'S láskou, Isabella',
        'footer_info_title':       'INFORMACE',
        'footer_faq_link':         'Časté dotazy',
        'footer_story_link':       'Náš Příběh',
        'footer_legal_link':       'Právní upozornění',
        'footer_terms_link':       'Obchodní podmínky',
        'footer_returns_link':     'Zásady vrácení',
        'footer_service_title':    'ZÁKAZNICKÁ PODPORA',
        'footer_service_text1':    'Máte otázku nebo potřebujete pomoc?',
        'footer_service_text2':    'Náš tým je tu pro vás.',
        'footer_hours':            'Pondělí – Pátek: 10:00 – 18:00',
        'footer_copyright':        '© 2026 Isabella Barcelona · Všechna práva vyhrazena',

        # ── Exit popup ────────────────────────────────────────────────────────
        'exit_tagline':       'Ještě neodcházejte',
        'exit_title':         'Počkejte! Váš košík<br>na vás čeká',
        'exit_text':          'Jako speciální dárek použijte tento exkluzivní kód a získejte 10% slevu na vaši objednávku:',
        'exit_code_label':    'Váš exkluzivní kód',
        'exit_discount_txt':  '10% sleva na vaši objednávku',
        'exit_cta':           'Chci svou slevu →',
        'exit_dismiss':       'Ne díky — raději zaplatím víc',
    },
}


def site_preferences(request):
    lang = request.session.get('site_lang', 'es')
    return {
        'site_lang':     lang,
        'site_currency': request.session.get('site_currency', 'EUR'),
        'nav':           _UI.get(lang, _UI['es']),
    }
