# Generated by Django 5.2.11 on 2026-05-13 16:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('api_endpoint', models.URLField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('avg_shipping_days', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dodavatel',
                'verbose_name_plural': 'Dodavatelé',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('customer_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='ES', max_length=2)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Zákazník'), ('ADMIN', 'Administrátor'), ('SUPPORT', 'Zákaznická podpora')], default='CUSTOMER', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Uživatel',
                'verbose_name_plural': 'Uživatelé',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Čeká na platbu'), ('PAID', 'Zaplaceno'), ('SHIPPED', 'Odesláno'), ('DELIVERED', 'Doručeno'), ('CANCELLED', 'Stornováno')], default='PENDING', max_length=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=4.9, max_digits=6)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('COD', 'Dobírka')], max_length=10)),
                ('shipping_name', models.CharField(max_length=120)),
                ('shipping_street', models.CharField(max_length=120)),
                ('shipping_city', models.CharField(max_length=60)),
                ('shipping_postal', models.CharField(max_length=10)),
                ('shipping_country', models.CharField(default='ES', max_length=2)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objednávka',
                'verbose_name_plural': 'Objednávky',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name_es', models.CharField(max_length=150)),
                ('description_es', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('PENDIENTES', 'Náušnice'), ('COLLARES', 'Náhrdelníky'), ('BRAZALETES', 'Náramky'), ('ANILLOS', 'Prsteny'), ('ACCESORIOS', 'Doplňky')], max_length=15)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.supplier')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-created_at'],
            },
        ),
    ]
